/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as BountiesIndexRouteImport } from './routes/bounties.index'
import { Route as BountiesKeyRouteImport } from './routes/bounties.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesIndexRoute = BountiesIndexRouteImport.update({
  id: '/bounties/',
  path: '/bounties/',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesKeyRoute = BountiesKeyRouteImport.update({
  id: '/bounties/$key',
  path: '/bounties/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/partners': typeof PartnersRoute
  '/replays': typeof ReplaysRoute
  '/bounties/$key': typeof BountiesKeyRoute
  '/bounties/': typeof BountiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/partners': typeof PartnersRoute
  '/replays': typeof ReplaysRoute
  '/bounties/$key': typeof BountiesKeyRoute
  '/bounties': typeof BountiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/partners': typeof PartnersRoute
  '/replays': typeof ReplaysRoute
  '/bounties/$key': typeof BountiesKeyRoute
  '/bounties/': typeof BountiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/challenges'
    | '/partners'
    | '/replays'
    | '/bounties/$key'
    | '/bounties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/challenges'
    | '/partners'
    | '/replays'
    | '/bounties/$key'
    | '/bounties'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/challenges'
    | '/partners'
    | '/replays'
    | '/bounties/$key'
    | '/bounties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  ChallengesRoute: typeof ChallengesRoute
  PartnersRoute: typeof PartnersRoute
  ReplaysRoute: typeof ReplaysRoute
  BountiesKeyRoute: typeof BountiesKeyRoute
  BountiesIndexRoute: typeof BountiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/': {
      id: '/bounties/'
      path: '/bounties'
      fullPath: '/bounties/'
      preLoaderRoute: typeof BountiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/$key': {
      id: '/bounties/$key'
      path: '/bounties/$key'
      fullPath: '/bounties/$key'
      preLoaderRoute: typeof BountiesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  ChallengesRoute: ChallengesRoute,
  PartnersRoute: PartnersRoute,
  ReplaysRoute: ReplaysRoute,
  BountiesKeyRoute: BountiesKeyRoute,
  BountiesIndexRoute: BountiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
